services:
  redis:
    image: redis:latest
    container_name: mu-redis
    ports:
      - "6379:6379"
    volumes:
      - ./acl.conf:/data/acl.conf
    command: >
      redis-server --aclfile /data/acl.conf
