package models

type Season struct {
	SeasonID     int    `json:"season_id"`
	SeasonName   string `json:"season_name"`
	SeasonNumber int    `json:"season_number"`
	SeasonTheme  string `json:"season_theme"`
	StartDate    string `json:"start_season_date"`
	EndDate      string `json:"end_season_date"`
	Active       string `json:"active"`
	UpdatedDate  string `json:"updated_date"`
}

type RankingReward struct {
	Rank                       int    `json:"rank"`
	Amount                     int    `json:"amount"`
	ItemNumber                 int    `json:"item_number"`
	ItemName                   string `json:"item_name"`
	ItemName2                  string `json:"item_name2"`
	Description                string `json:"description"`
	ItemNameTHAI               string `json:"item_name_THAI"`
	ItemName2THAI              string `json:"item_name2_THAI"`
	DescriptionTHAI            string `json:"description_THAI"`
	Kind                       int    `json:"kind"`
	Promotion                  int    `json:"promotion"`
	Level                      int    `json:"level"`
	Bone                       int    `json:"bone"`
	Style                      int    `json:"style"`
	Attach                     int    `json:"attach"`
	BuyPoint                   int    `json:"buy_point"`
	SellPoint                  int    `json:"sell_point"`
	ColorType                  int    `json:"color_type"`
	Experience                 int    `json:"experience"`
	Point                      int    `json:"point"`
	FileName1                  string `json:"file_name1"`
	FileName2                  string `json:"file_name2"`
	Reserv1                    int    `json:"reserv1"`
	Reserv2                    int    `json:"reserv2"`
	Reserv3                    int    `json:"reserv3"`
	Reserv4                    string `json:"reserv4"`
	Reserv5                    string `json:"reserv5"`
	NeedATKSTR                 int    `json:"needATK_STR"`
	NeedATKGRA                 int    `json:"needATK_GRA"`
	NeedDEFSTR                 int    `json:"needDEF_STR"`
	NeedDEFGRA                 int    `json:"needDEF_GRA"`
	NeedCRI                    int    `json:"needCRI"`
	NeedHP                     int    `json:"needHP"`
	NeedSP                     int    `json:"needSP"`
	NeedDEX                    int    `json:"needDEX"`
	NeedDEF                    int    `json:"needDEF"`
	NeedATK                    int    `json:"needATK"`
	GainATKSTR                 int    `json:"gainATK_STR"`
	GainATKGRA                 int    `json:"gainATK_GRA"`
	GainDEFSTR                 int    `json:"gainDEF_STR"`
	GainDEFGRA                 int    `json:"gainDEF_GRA"`
	GainCRI                    int    `json:"gainCRI"`
	GainHP                     int    `json:"gainHP"`
	GainSP                     int    `json:"gainSP"`
	GainDEX                    int    `json:"gainDEX"`
	GainDEF                    int    `json:"gainDEF"`
	GainATK                    int    `json:"gainATK"`
	PropIndex01                int    `json:"prop_index_01"`
	PropValue01                int    `json:"prop_value_01"`
	PropIndex02                int    `json:"prop_index_02"`
	PropValue02                int    `json:"prop_value_02"`
	PropIndex03                int    `json:"prop_index_03"`
	PropValue03                int    `json:"prop_value_03"`
	PropIndex04                int    `json:"prop_index_04"`
	PropValue04                int    `json:"prop_value_04"`
	PropIndex05                int    `json:"prop_index_05"`
	PropValue05                int    `json:"prop_value_05"`
	TranslateType              int    `json:"translate_type"`
	TranslateTypeTHAI          int    `json:"translate_type_THAI"`
	UpdateCountItemName        int    `json:"update_count_item_name"`
	UpdateCountItemName2       int    `json:"update_count_item_name2"`
	UpdateCountDescription     int    `json:"update_count_description"`
	UpdateCountItemNameTHAI    int    `json:"update_count_item_name_THAI"`
	UpdateCountItemName2THAI   int    `json:"update_count_item_name2_THAI"`
	UpdateCountDescriptionTHAI int    `json:"update_count_description_THAI"`
	OrbGroup                   int    `json:"orb_group"`
}

type RankingRewardSeasonRank struct {
	MinRank                    int    `json:"min_rank"`
	MaxRank                    int    `json:"max_rank"`
	ItemAmount                 int    `json:"item_amount"`
	ItemNumber                 int    `json:"item_number"`
	ItemName                   string `json:"item_name"`
	ItemName2                  string `json:"item_name2"`
	Description                string `json:"description"`
	ItemNameTHAI               string `json:"item_name_THAI"`
	ItemName2THAI              string `json:"item_name2_THAI"`
	DescriptionTHAI            string `json:"description_THAI"`
	Kind                       int    `json:"kind"`
	Promotion                  int    `json:"promotion"`
	Level                      int    `json:"level"`
	Bone                       int    `json:"bone"`
	Style                      int    `json:"style"`
	Attach                     int    `json:"attach"`
	BuyPoint                   int    `json:"buy_point"`
	SellPoint                  int    `json:"sell_point"`
	ColorType                  int    `json:"color_type"`
	Experience                 int    `json:"experience"`
	Point                      int    `json:"point"`
	FileName1                  string `json:"file_name1"`
	FileName2                  string `json:"file_name2"`
	Reserv1                    int    `json:"reserv1"`
	Reserv2                    int    `json:"reserv2"`
	Reserv3                    int    `json:"reserv3"`
	Reserv4                    string `json:"reserv4"`
	Reserv5                    string `json:"reserv5"`
	NeedATKSTR                 int    `json:"needATK_STR"`
	NeedATKGRA                 int    `json:"needATK_GRA"`
	NeedDEFSTR                 int    `json:"needDEF_STR"`
	NeedDEFGRA                 int    `json:"needDEF_GRA"`
	NeedCRI                    int    `json:"needCRI"`
	NeedHP                     int    `json:"needHP"`
	NeedSP                     int    `json:"needSP"`
	NeedDEX                    int    `json:"needDEX"`
	NeedDEF                    int    `json:"needDEF"`
	NeedATK                    int    `json:"needATK"`
	GainATKSTR                 int    `json:"gainATK_STR"`
	GainATKGRA                 int    `json:"gainATK_GRA"`
	GainDEFSTR                 int    `json:"gainDEF_STR"`
	GainDEFGRA                 int    `json:"gainDEF_GRA"`
	GainCRI                    int    `json:"gainCRI"`
	GainHP                     int    `json:"gainHP"`
	GainSP                     int    `json:"gainSP"`
	GainDEX                    int    `json:"gainDEX"`
	GainDEF                    int    `json:"gainDEF"`
	GainATK                    int    `json:"gainATK"`
	PropIndex01                int    `json:"prop_index_01"`
	PropValue01                int    `json:"prop_value_01"`
	PropIndex02                int    `json:"prop_index_02"`
	PropValue02                int    `json:"prop_value_02"`
	PropIndex03                int    `json:"prop_index_03"`
	PropValue03                int    `json:"prop_value_03"`
	PropIndex04                int    `json:"prop_index_04"`
	PropValue04                int    `json:"prop_value_04"`
	PropIndex05                int    `json:"prop_index_05"`
	PropValue05                int    `json:"prop_value_05"`
	TranslateType              int    `json:"translate_type"`
	TranslateTypeTHAI          int    `json:"translate_type_THAI"`
	UpdateCountItemName        int    `json:"update_count_item_name"`
	UpdateCountItemName2       int    `json:"update_count_item_name2"`
	UpdateCountDescription     int    `json:"update_count_description"`
	UpdateCountItemNameTHAI    int    `json:"update_count_item_name_THAI"`
	UpdateCountItemName2THAI   int    `json:"update_count_item_name2_THAI"`
	UpdateCountDescriptionTHAI int    `json:"update_count_description_THAI"`
	OrbGroup                   int    `json:"orb_group"` // ใช้ *string เพื่อรองรับค่า NULL
}

type RankingBoard struct {
	RankID        int    `json:"rank_id"`
	RankName      string `json:"rank_name"`
	Level         int    `json:"level"`
	PlayerStars   int    `json:"player_stars"`
	CurrentRank   int    `json:"current_rank"`
	CharacterName string `json:"character_name"`
	CharacterType int    `json:"character_type"`
	CharacterKey  int    `json:"character_key"`
	ClassType     int    `json:"class_type"`
	JobType       int    `json:"job_type"`
}
